declare class Address {
    merge_sub_and_building: boolean;
    cache: any;
    postcode_inward: string;
    postcode_outward: string;
    longitude: string | number;
    latitude: string | number;
    udprn: string | number;
    umprn: string | number;
    po_box: string | number;
    northings: string;
    eastings: string;
    postcode: string;
    post_town: string;
    dependant_locality: string;
    double_dependant_locality: string;
    thoroughfare: string;
    dependant_thoroughfare: string;
    building_number: string;
    building_name: string;
    sub_building_name: string;
    department_name: string;
    organisation_name: string;
    postcode_type: string;
    su_organisation_indicator: string;
    delivery_point_suffix: string;
    county: string;
    traditional_county: string;
    administrative_county: string;
    postal_county: string;
    district: string;
    ward: string;
    country: string;
    constructor(data: any);
    extractAddress(data: any): void;
    detectedMergedNumbers(): void;
    upcasePostTown(): void;
    assignOutcodes(): void;
    formattedAddress(): any;
    static formatPostcode(postcode: any): any;
    static sort(a: any, b: any): number;
}
export = Address;
