import * as t from "./types";
export declare class Address {
    readonly merge_sub_and_building: boolean;
    readonly postcode_inward: string;
    readonly postcode_outward: string;
    readonly po_box: string;
    readonly postcode: string;
    readonly post_town: string;
    readonly dependant_locality: string;
    readonly double_dependant_locality: string;
    readonly thoroughfare: string;
    readonly dependant_thoroughfare: string;
    readonly building_number: string;
    readonly building_name: string;
    readonly sub_building_name: string;
    readonly department_name: string;
    readonly organisation_name: string;
    readonly postcode_type: string;
    readonly su_organisation_indicator: string;
    readonly delivery_point_suffix: string;
    readonly county: string;
    readonly traditional_county: string;
    readonly administrative_county: string;
    readonly postal_county: string;
    readonly district: string;
    readonly ward: string;
    readonly country: string;
    readonly northings: number | t.EmptyString;
    readonly eastings: number | t.EmptyString;
    readonly udprn: number | t.EmptyString;
    readonly umprn: number | t.EmptyString;
    readonly longitude: number | t.EmptyString;
    readonly latitude: number | t.EmptyString;
    private cache;
    constructor(data: AddressRecord);
    raw(): t.RawAddress;
    toJSON(): t.AddressJSON;
    formattedAddress(): t.FormattedAddress;
    static formatPostcode(postcode: string): string;
    static sort(a: Address, b: Address): number;
}
export declare type AddressRecord = t.AddressRecord;
