import { Address } from "./index";
import * as t from "./types";
export declare const nameException: (n: string) => boolean;
export declare const appendOrganisationInfo: (elems: string[], address: Address) => void;
export declare const combinePremise: (elems: string[], address: Address, premise: string) => t.FormattedPremise;
export declare const premiseLocalities: (address: Address) => string[];
export declare const rule1: t.AddressFormatter;
export declare const rule2: t.AddressFormatter;
export declare const checkBuildingRange: (building_name: string) => t.BuildingRangeMatch | null;
export declare const rule3: t.AddressFormatter;
export declare const rule4: t.AddressFormatter;
export declare const rule5: t.AddressFormatter;
export declare const rule6: t.AddressFormatter;
export declare const rule7: t.AddressFormatter;
export declare const undocumentedRule: t.AddressFormatter;
export declare const po_box: t.AddressFormatter;
export declare const formatter: t.AddressFormatter;
